# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8989fd8ccedc0db376f6d88a7b39a4a5eea4de61036a72b9a3aab13e434fe4832b41f44b3d1a9fc7bd59334d7b1e798c605e3baad28a00aaf279cf175ac6ed4f

test:
  secret_key_base: ea84e2c308c5b57489f85218fbe2d69b6367fb82ca408cd8ea8b5582579e0a9f888cfc77e02cb7d866a80c704be22a8aa3a31c0297ef2bf406390dd107da657e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
